SELECT NAME
     , TEL
     , POSITION
     , TO_CHAR(PAY,'999,999,999,999') "PAY"
     , RANK() OVER(PARTITION BY SUBSTR(TEL,1,INSTR(TEL,')')-1), POSITION 
                        ORDER BY PAY DESC) "RANK"
  FROM EMP2;

SELECT NAME
     , BIRTHDAY
     , EMP_TYPE
     , TO_CHAR(PAY,'999,999,999') "PAY"
     , TO_CHAR(SUM(PAY) OVER(PARTITION BY EMP_TYPE 
                                  ORDER BY PAY DESC),'999,999,999') "TOTAL"
  FROM EMP2;

SELECT NAME
     , EMAIL
     , SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) "DOMAIN"
     , PAY
     , RANK() OVER(PARTITION BY SUBSTR(EMAIL,INSTR(EMAIL,'@')+1) ORDER BY PAY DESC) "RANK"
  FROM PROFESSOR;
  
SELECT NAME
     , HPAGE
     , SUBSTR(HPAGE,INSTR(HPAGE,'.',1)+1) "DOMAIN"
     , PAY
     , SUM(PAY) OVER(PARTITION BY SUBSTR(HPAGE,INSTR(HPAGE,'.',1)+1) ORDER BY PAY DESC)"TOTAL"
  FROM PROFESSOR
 WHERE HPAGE IS NOT NULL;

SELECT * FROM DEPARTMENT;

SELECT S.NAME "STU_NAME"
     , S.DEPTNO1 "DEPTNO1"
     , D.DNAME "DEPT_NAME"
  FROM STUDENT S, DEPARTMENT D
 WHERE S.DEPTNO1=D.DEPTNO;

SELECT S.NAME "STU_NAME"
     , S.DEPTNO1 "DEPTNO1"
     , D.DNAME "DEPT_NAME"
  FROM STUDENT S JOIN DEPARTMENT D
    ON D.DEPTNO=S.DEPTNO1;

SELECT * FROM P_GRADE;

SELECT NAME
     , E.POSITION
     , TO_CHAR(PAY,'999,999,999') "PAY"
     , TO_CHAR(S_PAY,'999,999,999') "LOW PAY"
     , TO_CHAR(E_PAY,'999,999,999') "HIGH PAY"
  FROM EMP2    E
     , P_GRADE P
     WHERE E.POSITION=P.POSITION;
     
SELECT NAME
     , BIRTHDAY
     , TO_CHAR(SYSDATE,'YYYY') -('1900'+SUBSTR(BIRTHDAY,1,2)) "AGE"
     , E.POSITION "CURR_POSITION"
     , P.POSITION "BE_POSITION"
  FROM EMP2 E,P_GRADE P
 WHERE TO_CHAR(SYSDATE,'YYYY') -('1900'+SUBSTR(BIRTHDAY,1,2)) BETWEEN P.S_AGE AND P.E_AGE; 
 
SELECT E.NAME
     , E.BIRTHDAY
     , TRUNC((SYSDATE - E.BIRTHDAY)/365,0) "AGE"
     , E.POSITION "CURR_POSITION"
     , P.POSITION "BE_POSITION"
  FROM EMP2 E,P_GRADE P
 WHERE TRUNC((SYSDATE - E.BIRTHDAY)/365,0) BETWEEN P.S_AGE AND P.E_AGE;  

SELECT * FROM CUSTOMER;
SELECT * FROM GIFT;

SELECT C.GNAME "CUST_NAME"
     , C.POINT
     , G.GNAME "GIFT_NAME" 
  FROM CUSTOMER C
     , GIFT     G
 WHERE C.POINT> G_START 
   AND G.GNAME='Notebook';

SELECT * FROM EMP2;

SELECT * FROM PROFESSOR;

SELECT P1.PROFNO
     , P1.NAME
     , TO_CHAR(P1.HIREDATE,'YYYY/MM/DD') "HIREDATE"
     , COUNT(P2.HIREDATE) "COUNT"
  FROM PROFESSOR P1, PROFESSOR P2
  WHERE P1.HIREDATE<P2.HIREDATE(+)
  GROUP BY P1.PROFNO,P1.NAME,P1.HIREDATE
  ORDER BY P1.HIREDATE DESC;
--  ORDER BY 4;

SELECT * FROM EMP;

SELECT E1.EMPNO
     , E1.ENAME
     , TO_CHAR(E1.HIREDATE,'YY/MM/DD') "HIREDATE"
     , COUNT(E2.HIREDATE) "COUNT"
  FROM EMP E1
     , EMP E2
 WHERE E1.HIREDATE>E2.HIREDATE(+)
 GROUP BY E1.EMPNO
        , E1.ENAME
        , E1.HIREDATE
 ORDER BY E1.HIREDATE;
 
SELECT E1.EMPNO
     , E1.ENAME
     , E1.HIREDATE
     , COUNT(E2.HIREDATE)
  FROM EMP E1
  LEFT OUTER JOIN EMP E2
    ON E1.HIREDATE>E2.HIREDATE
 GROUP BY E1.EMPNO,E1.ENAME,E1.HIREDATE
 ORDER BY E1.HIREDATE;