SELECT * FROM NEW_EMP11;


CREATE TABLE NEW_EMP11
(NO NUMBER(4) PRIMARY KEY
,NAME VARCHAR2(20) NOT NULL 
--   '-'하이픈은 주민번호, 전화번호에서는 데이터로 관리 안 함
,JUMIN VARCHAR2(13) NOT NULL UNIQUE -- =PRIMARY KEY인데 주민번호는 프라이머리로 잘 안건다
,LOC_CODE NUMBER(1) CHECK(LOC_CODE<5) --0~9까지인데 제약조건 때문에 0~4까지 5개
,DEPTNO VARCHAR2(6) REFERENCES DEPT2(DCODE)
);

ALTER TABLE NEW_EMP11
ADD CONSTRAINT NEW_EMP11_UK UNIQUE(NAME);

ALTER TABLE NEW_EMP11
MODIFY(LOC_CODE CONSTRAINT NEW_EMP11_NN NOT NULL);
