SELECT * FROM EMP;

SELECT * FROM STUDENT;

SELECT * FROM FRUIT;

SELECT * FROM LOAN;

SELECT * FROM PROFESSOR;

SELECT * FROM MEMBER;

SELECT * FROM CUSTOMER;

SELECT * FROM PROFESSOR3;

ALTER TABLE PROFESSOR3
DROP COLUMN CHECK_CARD_YN;

DESC PROFESSOR3;

ALTER TABLE PROFESSOR3
MODIFY(EMAIL VARCHAR2(100));

ALTER TABLE PROFESSOR3
RENAME COLUMN CARD_YN TO CHECK_CARD_YN ;

CREATE TABLE PROFESSOR4
AS
SELECT * FROM PROFESSOR3 WHERE 1=2;

SELECT * FROM PROFESSOR2;
DESC PROFESSOR2;

CREATE TABLE PROFESSOR2
(PROFNO NUMBER(8)
,NAME VARCHAR2(30)
,ID VARCHAR2(20)
,POSITION VARCHAR2(50)
,PAY NUMBER(5)
,HIREDATE DATE
,BONUS NUMBER(5)
,DEPTNO NUMBER(3)
,EMAIL VARCHAR2(100)
,HPAGE VARCHAR2(100)
);

SELECT * FROM PROFESSOR3;

ALTER TABLE PROFESSOR3
ADD(CART_YN CHAR(1) DEFAULT 'N');

CREATE TABLE PROFESSOR3 AS
SELECT PROFNO,NAME,EMAIL FROM PROFESSOR;



SELECT GNAME
     , POINT
     , CASE
             WHEN POINT BETWEEN 1 AND 99999 THEN 'C'
             WHEN POINT BETWEEN 100000 AND 299999 THEN 'B'
             WHEN POINT BETWEEN 300000 AND 600000 THEN 'A'
             WHEN POINT>600000 THEN 'S'
       END "CLASS"
  FROM CUSTOMER
 ORDER BY POINT DESC;

SELECT EMAIL
     , DECODE(LENGTH(SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1))
     , 4, REPLACE(EMAIL,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1),'????')
     , 6, REPLACE(EMAIL,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1),'??????')
     , 7, REPLACE(EMAIL,SUBSTR(EMAIL,1,INSTR(EMAIL,'@')-1),'???????')) "EMAIL_?"
     , HPAGE
     , DECODE(LENGTH(SUBSTR(HPAGE,INSTR(HPAGE,'.')+1))
     , 7, REPLACE(HPAGE,SUBSTR(HPAGE,INSTR(HPAGE,'.')+1,3),'***')
     , 9, REPLACE(HPAGE,SUBSTR(HPAGE,INSTR(HPAGE,'.')+1,5),'*****')) "HAPGE_*"
  FROM PROFESSOR
  WHERE HPAGE IS NOT NULL;

SELECT NAME
     , WEIGHT
     , JUMIN
     , REPLACE(JUMIN,SUBSTR(JUMIN,7),'*******') "SECURE"
  FROM STUDENT
 WHERE WEIGHT<70;

SELECT NAME
     , HPAGE
     , SUBSTR(HPAGE,INSTR(HPAGE,'/')+2,INSTR(HPAGE,'.')-2-(INSTR(HPAGE,'/'))) "WWW"
  FROM PROFESSOR
 WHERE HPAGE IS NOT NULL;

SELECT NAME
     , POSITION
     , INSTR(POSITION,'p') "P"
     , EMAIL
  FROM PROFESSOR
 WHERE EMAIL LIKE '%net';

SELECT NAME
     , SUBSTR(JUMIN, 3 , 2)"MONTH"
     , AN_KEY_DAP
  FROM MEMBER
  WHERE AN_KEY_DAP LIKE 'Ni%';

SELECT DEPTNO
     , NAME
     , PAY
     , SUM(PAY) OVER(PARTITION BY DEPTNO) "TOTAL_DEPTNO"
     , ROUND(RATIO_TO_REPORT(SUM(PAY)) OVER(PARTITION BY DEPTNO)*100,2) "RATIO (%)"
  FROM PROFESSOR
 GROUP BY DEPTNO, NAME, PAY 
 ORDER BY 1;

SELECT DEPTNO
     , NAME
     , PAY
     , SUM(PAY) OVER() "TOTAL PAY"
     , ROUND(RATIO_TO_REPORT(SUM(PAY)) OVER()*100,2) "RATIO %"
  FROM PROFESSOR
 GROUP BY DEPTNO, NAME, PAY 
 ORDER BY PAY DESC;

SELECT L_CODE "대출종목코드"
     , L_STORE "대출지점"
     , L_DATE "대출일자"
     , L_QTY "대출건수"
     , L_TOTAL "대출액"
     , SUM(L_TOTAL) OVER(PARTITION BY L_CODE,L_STORE ORDER BY L_DATE) "누적대출금액"
  FROM LOAN;

SELECT L_DATE "대출일자"
     , L_CODE "대출종목코드"
     , L_QTY "대출건수"
     , L_TOTAL "대출총액"
     , SUM(L_TOTAL) OVER(ORDER BY L_DATE) "누적대출금액"
  FROM LOAN
  WHERE L_STORE=1000;

SELECT DEPTNO
     , ENAME
     , SAL
     , SUM(SAL) OVER(PARTITION BY DEPTNO) "SUM_DEPT"
     , ROUND((RATIO_TO_REPORT(SUM(SAL)) OVER (PARTITION BY DEPTNO)) *100,2) "%"
  FROM EMP
 GROUP BY DEPTNO,ENAME,SAL
 ORDER BY DEPTNO;

SELECT DEPTNO
     , ENAME
     , SAL
     , SUM(SAL) OVER() "TOTAL_SAL"
     , ROUND((RATIO_TO_REPORT(SUM(SAL)) OVER ()) *100,2) "%"
--     , ROUND(SAL/SUM(SAL) OVER()*100,2)"%"
  FROM EMP
 GROUP BY DEPTNO,ENAME,SAL
 ORDER BY SAL DESC;
  
SELECT DEPTNO
     , ENAME
     , SAL
     , SUM(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL) "TOTAL"
  FROM EMP;

SELECT COUNT(*)||'EA ('||COUNT(*)/COUNT(*)*100||'%)'  AS "TOTAL"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',1))
        ||'EA ('
        ||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',1))/COUNT(*)*100
        ||'%)' AS"SEOUL"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',1))
        ||'EA ('
        ||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',1))/COUNT(*)*100
        ||'%)' AS"GYEONGGI"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'051',1))
        ||'EA ('
        ||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'051',1))/COUNT(*)*100
        ||'%)' AS"BUSAN"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',1))
        ||'EA ('
        ||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',1))/COUNT(*)*100
        ||'%)' AS"ULSAN"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',1))
        ||'EA ('
        ||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',1))/COUNT(*)*100
        ||'%)' AS"DAEGU"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',1))
        ||'EA ('
        ||COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',1))/COUNT(*)*100
        ||'%)' AS"GYEONGNAM"
--     , ROUND(COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',1))/COUNT(*) OVER()*100,2)
  FROM STUDENT; 

SELECT max(decode(name,'apple',PRICE)) "APPLE"
     , max(decode(name,'grape',PRICE)) "GRAPE"
     , max(decode(name,'orange',PRICE)) "ORANGE"
  FROM FRUIT;

SELECT max(decode(name,'apple',100)) "APPLE"
     , max(decode(name,'grape',200)) "GRAPE"
     , max(decode(name,'orange',300)) "ORANGE"
  FROM FRUIT;

SELECT max(decode(regexp_count(name,'apple'))) "APPLE"
     , max(regexp_count(name,'grape')) "GRAPE"
     , max(regexp_count(name,'orange')) "ORANGE"
  FROM FRUIT;

SELECT DEPTNO
     , ENAME
     , SAL
     , SUM(SAL) OVER(ORDER BY SAL) "TOTAL"
  FROM EMP;

SELECT COUNT(*) AS "TOTAL"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'02',1)) AS"SEOUL"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'031',1)) AS"GYEONGGI"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'051',1)) AS"BUSAN"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'052',1)) AS"ULSAN"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'053',1)) AS"DAEGU"
     , COUNT(DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),'055',1)) AS"GYEONGNAM"
  FROM STUDENT;

SELECT COUNT(*) ||'EA' AS "TOTAL"
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'01',1))||'EA' AS "JAN" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'02',1))||'EA' AS "FEB" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'03',1))||'EA' AS "MAR" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'04',1))||'EA' AS "APR" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'05',1))||'EA' AS "MAY" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'06',1))||'EA' AS "JUN" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'07',1))||'EA' AS "JUL" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'08',1))||'EA' AS "AUG" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'09',1))||'EA' AS "SEP" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'10',1))||'EA' AS "OCT" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'11',1))||'EA' AS "NOV" 
      , COUNT(DECODE(TO_CHAR(BIRTHDAY,'MM'),'12',1))||'EA' AS "DEC" 
FROM STUDENT;

SELECT COUNT(*) ||'EA' AS "TOTAL"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'01'))||'EA' AS "JAN" 
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'02'))||'EA' AS "FEB" 
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'03'))||'EA' AS "MAR" 
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'04'))||'EA' AS "APR"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'05'))||'EA' AS "MAY"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'06'))||'EA' AS "JUN"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'07'))||'EA' AS "JUL"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'08'))||'EA' AS "AUG"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'09'))||'EA' AS "SEP"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'10'))||'EA' AS "OCT"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'11'))||'EA' AS "NOV"
      , SUM(regexp_count(SUBSTR(BIRTHDAY,4,2),'12'))||'EA' AS "DEC"
FROM STUDENT;

SELECT MAX(SAL+NVL(COMM, 0)) MAX
      , MIN(SAL+NVL(COMM, 0)) MIN
      , ROUND(AVG(SAL+NVL(COMM, 0)),1) AVG
  FROM EMP;