SELECT GNAME
     , JUMIN
     , SUBSTR(GNAME,1,3)||337||SUBSTR(GNAME,7) "337"
  FROM CUSTOMER
  WHERE SUBSTR(JUMIN,1,2)<77;

SELECT GNAME
     , SUBSTR(JUMIN,1,2) YEAR
     , POINT
  FROM CUSTOMER
 WHERE (POINT>=100000)
 ORDER BY POINT DESC;