SELECT * FROM PANMAE;



SELECT P_CODE
     , P_STORE
     , P_QTY
     , SUM(P_QTY) OVER() "TOTAL_QTY"
--     , ROUND(P_QTY/SUM(P_QTY) OVER()*100,2)"QTY_%"
     , ROUND((RATIO_TO_REPORT(SUM(P_QTY)) OVER())*100,2)"QTY_%"
  FROM PANMAE
  WHERE P_CODE=100
  GROUP BY P_CODE,P_STORE,P_QTY;
  
  ORDER BY P_STORE;

SELECT P_CODE
     , P_STORE
     , P_DATE
     , P_QTY
     , P_TOTAL
     , SUM(P_TOTAL) OVER(PARTITION BY P_CODE,P_STORE ORDER BY P_DATE) "TOTAL"
  FROM PANMAE;

SELECT P_DATE
     , P_CODE
     , P_QTY
     , P_TOTAL
     , SUM(P_TOTAL) OVER(PARTITION BY P_CODE ORDER BY P_TOTAL) "TOTAL"
  FROM PANMAE
 WHERE P_STORE=1000;

SELECT P_DATE
     , P_CODE
     , P_QTY
     , P_TOTAL
     , SUM(P_TOTAL) OVER(ORDER BY P_TOTAL) "TOTAL"
  FROM PANMAE
 WHERE P_STORE=1000;