SELECT * FROM STUDENT;

SELECT NAME
     , TEL
     , SUBSTR(TEL,INSTR(TEL,')')+1,(INSTR(TEL,'-')-1)-(INSTR(TEL,')'))) "GUK_NO"
  FROM STUDENT
  WHERE DEPTNO1=101;

SELECT NAME
     , GRADE
     , TEL
     , INSTR(TEL,'6') "6"
  FROM STUDENT
  WHERE GRADE IN ('2','4');

SELECT NAME
     , HEIGHT
     , SUBSTR(JUMIN,5,2) "DAY"
  FROM STUDENT
  WHERE HEIGHT>=180;

SELECT NAME
     , TEL
  FROM STUDENT
 WHERE REGEXP_LIKE(TEL,'^[0-9]{2}\)[0-9]{4}');
 
SELECT NAME
     , TEL
     , DECODE(SUBSTR(TEL,1,INSTR(TEL,')')-1),055,'GYEONGNAM',02,'SEOUL',031,'GYEONGGI',051,'BUSAN',052,'ULSAN')
  FROM STUDENT
  WHERE DEPTNO1=101;
  
SELECT NAME
     , TEL
  FROM STUDENT
 WHERE REGEXP_LIKE(SUBSTR(TEL,4,1),'[0-9]')
   AND REGEXP_LIKE(SUBSTR(TEL,4,4),'[0-9]{4}');


SELECT NAME
     , SUBSTR(JUMIN,3,2) MONT
     , CASE     WHEN SUBSTR(JUMIN,3,2) BETWEEN '01' AND '03' THEN '1/4'
                WHEN SUBSTR(JUMIN,3,2) BETWEEN '04' AND '06' THEN '2/4'
                WHEN SUBSTR(JUMIN,3,2) BETWEEN '07' AND '09' THEN '3/4'
                WHEN SUBSTR(JUMIN,3,2) BETWEEN '10' AND '12' THEN '4/4'
                END "Qua"
  FROM STUDENT;

SELECT NAME
     , TEL
     , CASE SUBSTR(TEL,1,INSTR(TEL,')')-1) WHEN '02' THEN 'SEOUL'
                                            WHEN '031' THEN 'GYEONGGI'
                                            WHEN '051' THEN 'BUSAN'
                                            WHEN '052' THEN 'ULSAN'
                                            WHEN '055' THEN 'GYEONGNAM'
                                            ELSE 'ETC'
                                            END "LOC"
  FROM STUDENT
 WHERE DEPTNO1=201;

SELECT NAME
     , ID
  FROM STUDENT
--  M으로 시작하고 그 다음에 a나 o 가 옴 
 WHERE REGEXP_LIKE(ID, '^M(a|o)');

SELECT NAME 이름
     , SUBSTR(JUMIN,3,2) 월
     , SUBSTR(JUMIN,5,2) 일
  FROM STUDENT
 WHERE DEPTNO1=101;
  
SELECT * FROM STUDENT;

SELECT PROFNO
     , NAME
  FROM PROFESSOR
 WHERE DEPTNO = 201
UNION
SELECT STUDNO
     , NAME
  FROM STUDENT
 WHERE DEPTNO1 = 201;



SELECT DEPTNO
FROM PROFESSOR
INTERSECT
SELECT DEPTNO
FROM DEPARTMENT
MINUS
SELECT DEPTNO1
FROM STUDENT;

SELECT NAME
     , ID
     , DEPTNO1
FROM STUDENT
WHERE NAME LIKE 'Bi%';

SELECT *
FROM STUDENT;

SELECT NAME
     , GRADE
     , HEIGHT
FROM STUDENT
WHERE height >= 165 AND HEIGHT <= 175;

SELECT NAME
     , ID
     , GRADE
FROM STUDENT
WHERE DEPTNO1 = 101 AND GRADE >= 3;

SELECT NAME
     , GRADE
     , height
FROM STUDENT
WHERE HEIGHT > 170
ORDER BY HEIGHT DESC;

SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno1 = 101
--INTERSECT
MINUS
SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno2 = 201;

SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno1 = 101
UNION ALL --6 (JAMES SEO 중복, 정렬 X)9411 9511 9611 9711 9411 9512
SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno2 = 201;

SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno1 = 101
UNION --5건 정렬 O --9411 9511 9512 9611 9711
SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno2 = 201;

--4
SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno1 = 101;
 
---2
SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno2 = 201;

SELECT STUDNO
     , NAME
FROM STUDENT
WHERE deptno1 = 101;

SELECT NAME 이름
     , SUBSTR(JUMIN,3,2) 월
     , SUBSTR(JUMIN,5,2) 일
  FROM STUDENT
 WHERE DEPTNO1=101;
  
SELECT * FROM STUDENT;

SELECT *
FROM STUDENT;