--PL/SQL--
--사원 급여 조정 프로시져
CREATE OR REPLACE PROCEDURE ADJUST_SAL
    (V_FLAG VARCHAR2, V_EMPNO NUMBER, V_PCT NUMBER) AS
BEGIN
    IF V_FLAG = 'INCREASE' THEN 
        UPDATE EMP SET SAL=SAL+(SAL*(V_PCT/100))
            WHERE EMPNO = V_EMPNO;
    ELSE
        UPDATE EMP SET SAL=SAL-(SAL*(V_PCT/100))
            WHERE EMPNO = V_EMPNO;
    END IF;
END;