--사원 입사일자 구하는 함수 ( EX.2025-03-11 ) VARCHAR2 필요하다
CREATE OR REPLACE FUNCTION GET_HIREDATE
    (V_EMPNO NUMBER,V_FMT VARCHAR2) RETURN VARCHAR2 IS V_HIREDATE VARCHAR2(20);
BEGIN
    SELECT TO_CHAR(HIREDATE,V_FMT)
      INTO V_HIREDATE
      FROM EMP
     WHERE EMPNO= V_EMPNO;
    RETURN V_HIREDATE;
END;