--패키지, 프로시져와 함수를 하나로 합치는 과정 
-- HEADER만 만들었다

CREATE OR REPLACE PACKAGE emp_mgmt AS
    PROCEDURE ADJUST_SAL(V_FLAG VARCHAR2, V_EMPNO NUMBER, V_PCT NUMBER);
    FUNCTION GET_ANNUAL_SAL(V_EMPNO NUMBER) RETURN NUMBER;
    FUNCTION GET_RETIRE_MONEY(V_EMPNO NUMBER) RETURN NUMBER;
    PROCEDURE REMOVE_EMP(V_EMPNO NUMBER);
    FUNCTION GET_HIREDATE(V_EMPNO NUMBER,V_FMT VARCHAR2) RETURN VARCHAR2;
END emp_mgmt;
