--PL/SQL--
--사원 퇴직급여 구하는 함수
CREATE OR REPLACE FUNCTION GET_RETIRE_MONEY
    (V_EMPNO NUMBER) RETURN NUMBER IS V_SAL NUMBER;
BEGIN
    SELECT ROUND((SAL+NVL(COMM,0)) * ROUND(MONTHS_BETWEEN(SYSDATE,HIREDATE),0)/12,0) INTO V_SAL
        FROM EMP
        WHERE EMPNO= V_EMPNO;
        RETURN V_SAL;
END;