SELECT * FROM STUDENT;

SELECT NAME
     , GRADE
     , WEIGHT
  FROM STUDENT
 WHERE WEIGHT<( SELECT MIN(WEIGHT)
                   FROM STUDENT
                  WHERE GRADE=2);

SELECT NAME
     , GRADE
     , WEIGHT
  FROM STUDENT
 WHERE WEIGHT< ALL( SELECT WEIGHT
                   FROM STUDENT
                  WHERE GRADE=2)
 ORDER BY 3 DESC;

SELECT MIN(WEIGHT)
  FROM STUDENT
 WHERE GRADE=2 ;
 
 ---------------
SELECT * FROM EMP2; --DEPTNO
SELECT * FROM DEPT2; --DCODE

SELECT D.DNAME
     , E.NAME
     , TO_CHAR(E.PAY,'$999,999,999') "SALARY"
  FROM EMP2 E,DEPT2 D
 WHERE D.DCODE=E.DEPTNO 
   AND E.PAY<(SELECT MIN(AVG(PAY))
                FROM EMP2 E
                GROUP BY DEPTNO)
 ORDER BY 3;

SELECT D.DNAME ,AVG(PAY)
FROM DEPT2 D, EMP2 E
WHERE D.DCODE=E.DEPTNO
GROUP BY D.DNAME,D.DCODE;

SELECT DEPTNO, AVG(PAY)
FROM EMP2 E
GROUP BY DEPTNO;

SELECT MIN(AVG(PAY))
                FROM EMP2 E
                GROUP BY DEPTNO;
                
-----------------

SELECT GRADE
     , NAME
     , WEIGHT
  FROM STUDENT
 WHERE (GRADE,WEIGHT) IN(SELECT GRADE
                               , MAX(WEIGHT)
                            FROM STUDENT
                           GROUP BY GRADE)
 ORDER BY 1;
 
SELECT MAX(WEIGHT)
  FROM STUDENT
 GROUP BY GRADE;
--------
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT P.PROFNO
     , P.NAME "PROF_NAME"
     , TO_CHAR(P.HIREDATE,'YYYY-MM-DD') "HIREDATE"
     , D.DNAME "DEPT_NAME"
  FROM PROFESSOR  P, DEPARTMENT D 
 WHERE D.DEPTNO=P.DEPTNO 
   AND (P.DEPTNO,P.HIREDATE) IN(SELECT P.DEPTNO
                                     , MIN(P.HIREDATE) 
                                  FROM PROFESSOR P 
                                 GROUP BY P.DEPTNO)
 ORDER BY 3;
     
SELECT P.DEPTNO,MIN(P.HIREDATE) FROM PROFESSOR P GROUP BY DEPTNO;    


------11번
SELECT * FROM EMP2;

SELECT NAME
     , POSITION
     , TO_CHAR(PAY, '$999,999,999')"SALARY"
  FROM EMP2
 WHERE POSITION IS NOT NULL AND PAY IN(SELECT MAX(PAY)
                                            FROM EMP2
                                           GROUP BY POSITION)
 ORDER BY 3;

SELECT NAME
     , POSITION
     , TO_CHAR(PAY, '$999,999,999')"SALARY"
  FROM EMP2
 WHERE (POSITION, PAY) IN(SELECT POSITION
                                 , MAX(PAY)
                              FROM EMP2
                             GROUP BY POSITION)
 ORDER BY 3;

SELECT MAX(PAY) FROM EMP2 GROUP BY POSITION;

---------
SELECT * FROM EMP;

SELECT DEPTNO
     , JOB
     , SAL
     , COUNT(*) OVER(PARTITION BY DEPTNO ORDER BY DEPTNO) "CNT_EMP"
  FROM EMP
--  WHERE (DEPTNO,JOB,SAL)IN(SELECT DEPTNO,JOB, ROUND(AVG(SAL),1) FROM EMP GROUP BY DEPTNO,JOB)
 ORDER BY DEPTNO;
 
SELECT DEPTNO
     , DECODE(DEPTNO, DEPTNO1, DEPTNO, NULL) DEPTNO1
  FROM(SELECT LAG(DEPTNO)OVER(PARTITION BY DEPTNO ORDER BY DEPTNO) DEPTNO1
         , DEPTNO
         , JOB
         , COUNT(*)
      FROM EMP
      GROUP BY DEPTNO,JOB);

SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY DEPTNO, JOB
-- ORDER BY DEPTNO
UNION ALL
SELECT DEPTNO
     , NULL JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY DEPTNO
UNION ALL
SELECT NULL DEPTNO
     , NULL JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 ORDER BY DEPTNO,JOB;
 
SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY ROLLUP(DEPTNO, JOB);
 
SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY DEPTNO, JOB
-- ORDER BY DEPTNO
UNION ALL
SELECT DEPTNO
     , NULL JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY DEPTNO
UNION ALL
SELECT NULL DEPTNO
     , JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY JOB
UNION ALL
SELECT NULL DEPTNO
     , NULL JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 ORDER BY DEPTNO,JOB;
 
SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL), 1)
     , COUNT(*)
  FROM EMP
  GROUP BY DEPTNO, JOB
UNION ALL
SELECT DEPTNO
     , NULL JOB
     , ROUND(AVG(SAL), 1)
     , COUNT(*)
  FROM EMP
  GROUP BY DEPTNO
UNION ALL
SELECT NULL DEPTNO
     , JOB
     , ROUND(AVG(SAL), 1)
     , COUNT(*)
  FROM EMP
  GROUP BY JOB
UNION ALL
SELECT NULL DEPTNO
     , NULL JOB
     , ROUND(AVG(SAL), 1)
     , COUNT(*)
  FROM EMP
  ORDER BY DEPTNO,JOB;

SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY CUBE(DEPTNO, JOB)
 ORDER BY DEPTNO;
 
SELECT NULL DEPTNO
     , JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY JOB
UNION ALL 
SELECT DEPTNO
     , NULL JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY DEPTNO
 ORDER BY DEPTNO,JOB;
 
SELECT DEPTNO
     , JOB
     , ROUND(AVG(SAL),1) "AVG_SAL"
     , COUNT(*) "CNT_EMP"
  FROM EMP
 GROUP BY GROUPING SETS(DEPTNO, JOB)
 ORDER BY DEPTNO,JOB;
 
SELECT GRADE
     , NULL DEPTNO1
     , COUNT(*)
     , SUM(HEIGHT) "TOTAL_HEIGHT"
     , SUM(WEIGHT) "TOTAL_WEIGHT"
  FROM STUDENT
 GROUP BY GRADE
UNION ALL 
SELECT NULL GRADE
     , DEPTNO1
     , COUNT(*)
     , SUM(HEIGHT) "TOTAL_HEIGHT"
     , SUM(WEIGHT) "TOTAL_WEIGHT"
  FROM STUDENT
 GROUP BY DEPTNO1
 ORDER BY GRADE,DEPTNO1;